# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mike/rotinom/fpga/rotinom.srcs/sources_1/ip/prop_clk_div/prop_clk_div.xci
# IP: The module: 'prop_clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mike/rotinom/fpga/rotinom.srcs/sources_1/ip/prop_clk_div/prop_clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clk_div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mike/rotinom/fpga/rotinom.srcs/sources_1/ip/prop_clk_div/prop_clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mike/rotinom/fpga/rotinom.srcs/sources_1/ip/prop_clk_div/prop_clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/mike/rotinom/fpga/rotinom.srcs/sources_1/ip/prop_clk_div/prop_clk_div.xci
# IP: The module: 'prop_clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mike/rotinom/fpga/rotinom.srcs/sources_1/ip/prop_clk_div/prop_clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mike/rotinom/fpga/rotinom.srcs/sources_1/ip/prop_clk_div/prop_clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mike/rotinom/fpga/rotinom.srcs/sources_1/ip/prop_clk_div/prop_clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
